services:
  - type: web
    name: accounting-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: accounting-db
          property: connectionString
      - key: FLASK_ENV
        value: production
    
  - type: pserv
    name: accounting-db
    env: postgresql
    plan: free
    databaseName: accounting_system
    user: accounting_user
